In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.25.2'

In [ ]:
l = [1,2,3,4,5]
arr = np.array(l)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [ ]:
arr.ndim

1

In [ ]:
print(np.array(l))

[1 2 3 4 5]


In [ ]:
l = [1,2,3,4,5,'kaleem']
arr1 = np.array(l)
print(arr1)

['1' '2' '3' '4' '5' 'kaleem']


In [ ]:
arr1

array(['1', '2', '3', '4', '5', 'kaleem'], dtype='<U21')

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2.ndim

2

In [ ]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr3.ndim

3

In [ ]:
mat = np.matrix([[1,2],[3,4],[5,6]])

In [ ]:
# more way to create list to array
arr4 = np.asarray([[1,2,3],[4,5,6]])
arr4.ndim

2

In [ ]:
# another way
arr5 = np.asanyarray([1,2,3])
arr5

array([1, 2, 3])

In [ ]:
np.asanyarray(mat)

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
np.array(mat)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
x = 10
np.asanyarray(x)

array(10)

In [ ]:
# Tuple to array
tup1 = (1,2,3,4,5)
type(tup1)
np.array(tup1)

array([1, 2, 3, 4, 5])

In [ ]:
# shallow copy
l = [1,2,3,4,5]
arr = np.array(l)
s = arr
arr[0] = 100
arr
s

array([100,   2,   3,   4,   5])

In [ ]:
# Deep copy
arr
new_arr = arr.copy()
new_arr[0] = 0
print(arr)
print(new_arr)

[100   2   3   4   5]
[0 2 3 4 5]


In [ ]:
# How to generate arrays in numpy
np.fromfunction(lambda x , y: x==y,shape = (2,2))

array([[ True, False],
       [False,  True]])

In [ ]:
new_arr.shape

(5,)

In [ ]:
arr3.shape

(1, 3, 3)

In [ ]:
arr.size

5

In [ ]:
iterable = [i*i for i in range(5)]

np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [ ]:
np.fromstring('123,456' , sep = ',')

array([123., 456.])

In [ ]:
np.fromstring('kaleem,shaheem,amit' , sep = ',')

<ipython-input-25-ccb404b94e38>:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('kaleem,shaheem,amit' , sep = ',')


array([], dtype=float64)

In [ ]:
list(range(0.1,10.1,2))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
# To overcome this problem we use np.arange()
list(np.arange(0.1,10.1,0.5))

[0.1,
 0.6,
 1.1,
 1.6,
 2.1,
 2.6,
 3.1,
 3.6,
 4.1,
 4.6,
 5.1,
 5.6,
 6.1,
 6.6,
 7.1,
 7.6,
 8.1,
 8.6,
 9.1,
 9.6]

In [ ]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.logspace(1,5,10,base = 10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [ ]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones((3,3),int)

In [ ]:
arr + 5

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [ ]:
# Restart video at 3:00

# Summary
1. np.array - To convert any datatype into array
2. np.asarray - another way to convert an array
3. np.asanyarray - It is also the way to convert the array but it will return same if the input is the subclass of array
4. Shallow copy - if you change the array it will reflect in another array also
5. Deep copy - if you change the array it will not reflect in another array
6. arr.shape - returns the dimension
7. arr.size - return the number of elements
8. arr.ndim - return the dimension of the array
9. fromfunction - to generate an array
10. fromiter - to generate an array using iterables
11. fromString - to generate an array using strings
12. np.arange - to generate an array of floating numbers which cannot be generated using range function.
13. np.linspace - it is used to generate an array between ranges such as create an array of 10 values between 1 to 5.
14. np.logspace - it is same as linespace but here it creates by taking the log values.\
15. np.zeros - to generate an array of values containing zeros.
16. np.ones - same as np.zeros but generates in value 1
17.